export const UNDEFINED = 'undefined';
export const STATUS_SUCCESS = 200;
export const STATUS_FAIL = 400;
export const RESULT_CODE_SUCCESS = 10001;
export const CHANGE_MSG_CODE = 'CHANGE_MSG_CODE';
export const MESSAGE_HEADER = 'MESSAGE_HEADER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const PROCESS_OTP_SUCCESS = 'PROCESS_OTP_SUCCESS';
export const PROCESS_OTP_FAIL = 'PROCESS_OTP_FAIL';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAIL = 'RESEND_OTP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';



