export const UNDEFINED = 'undefined';

export const STATUS_SUCCESS = 200;
export const STATUS_FAIL = 400;
export const RESULT_CODE_SUCCESS = 10001;

export const CHANGE_MSG_CODE = 'CHANGE_MSG_CODE';
export const MESSAGE_HEADER = 'MESSAGE_HEADER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const PROCESS_OTP_SUCCESS = 'PROCESS_OTP_SUCCESS';
export const PROCESS_OTP_FAIL = 'PROCESS_OTP_FAIL';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAIL = 'SEND_OTP_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const GET_JOBS_SUCCESS = 'GET_JOBS_SUCCESS';
export const GET_JOBS_FAIL = 'GET_JOBS_FAIL';
export const GET_JOBS_DETAIL_SUCCESS = 'GET_JOBS_DETAIL_SUCCESS';
export const GET_JOBS_DETAIL_FAIL = 'GET_JOBS_DETAIL_FAIL';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAIL = 'GET_USER_INFO_FAIL';
export const GET_USER_BASIC_INFO_SUCCESS = 'GET_USER_BASIC_INFO_SUCCESS';
export const GET_USER_BASIC_INFO_FAIL = 'GET_USER_BASIC_INFO_FAIL';

export const TYPE_USER_FORGOT_PASSWORD = 'forgot_password';
export const TYPE_USER_BASIC_DETAIL = 'basic_detail';
export const TYPE_USER_FULL_DETAIL = 'full_detail';
export const SEARCH_JOBS_SUCCESS = 'SEARCH_JOBS_SUCCESS';
export const SEARCH_JOBS_FAIL = 'SEARCH_JOBS_FAIL';
export const SEARCH_JOBS_DETAIL_SUCCESS = 'SEARCH_JOBS_DETAIL_SUCCESS';
export const SEARCH_JOBS_DETAIL_FAIL = 'SEARCH_JOBS_DETAIL_FAIL';
export const APPLY_JOBS_SUCCESS = 'APPLY_JOBS_SUCCESS';
export const APPLY_JOBS_FAIL = 'APPLY_JOBS_FAIL';
