export const demo = 'Ví dụ';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const select_location = 'Chọn địa điểm làm việc';
export const select_industry = 'Chọn nhóm ngành';
export const KEY_CHECK_LOGIN = 'KEY_CHECK_LOGIN';
export const VALUE_ONE = '1';
export const VALUE_ZERO = '0';
export const KEY_CHECK_LAST_RETRO = 'KEY_CHECK_LAST_RETRO';
export const ADDRESS_OF_RELATIVE = true;
