import {StyleSheet, Platform} from 'react-native';
import {getStatusBarHeight} from 'react-native-status-bar-height';
export default StyleSheet.create({
  container: {
    ...Platform.select({
      ios: {
        marginTop: getStatusBarHeight(),
        marginBottom: 50,
      },
    }),
  },
  viewEdit: {
    alignSelf: 'flex-end',
  },
  viewCircleAvatar: {
    alignItems: 'center',
    marginTop: 15,
    justifyContent: 'center',
  },
  circleAvatar: {
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
    position: 'absolute',
  },
  circleAvatarFill: {
    width: 95,
    height: 95,
    borderRadius: 95 / 2,
    position: 'absolute',
  },
  viewCamera: {
    width: 95,
    height: '100%',
    alignItems: 'flex-end',
    position: 'absolute',
  },
  boxCamera: {
    width: 30,
    height: 30,
    marginTop: 78,
    borderRadius: 30 / 2,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  name: {
    textAlign: 'center',
    color: '#1c1c1c',
    marginTop: 10,
    fontSize: 16,
    fontWeight: 'bold',
  },
  viewReward: {flexDirection: 'row', justifyContent: 'center'},
  boxReward: {
    backgroundColor: '#F0532D',
    flexDirection: 'row',
    alignSelf: 'flex-start',
    padding: 10,
    marginTop: 10,
    marginBottom: 15,
    borderRadius: 5,
  },
  boxRewardStar: {width: 20, height: 20, marginEnd: 10},
  boxRewardTextReward: {color: '#fff', fontSize: 14},
  boxRewardTextPoint: {color: '#fff', fontSize: 14, fontWeight: 'bold'},
  boxItem: {
    height: 45,
    flexDirection: 'row',
    paddingStart: 14,
    alignItems: 'center',
  },
  boxItemTitle: {color: '#1c1c1c', fontSize: 16, marginStart: 10},
  boxItemIndicator: {backgroundColor: '#d8d8d8', height: 1, marginStart: 14},
  txtSave: {
    color: '#F0532D',
    fontSize: 18,
    fontWeight: 'bold',
    padding: 16,
  },
  boxAddImage: {
    width: 80,
    height: 80,
    borderRadius: 6,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#e3e3e3',
    justifyContent: 'center',
    alignItems: 'center',
  },
  containerAddImage: {
    flexDirection: 'row',
    margin: 15,
    justifyContent: 'space-evenly',
  },
  boxShowImage: {flexDirection: 'row', justifyContent: 'flex-end'},
  imageLoad: {width: 80, height: 80, borderRadius: 6},
  boxClose: {
    width: 25,
    height: 25,
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
  },
  boxButtonAdd: {
    width: 70,
    height: 70,
    alignItems: 'center',
    justifyContent: 'center',
  },
  txtBasicInfo: {
    flex: 1,
    color: '#d8d8d8',
    fontSize: 16,
    fontWeight: 'bold',
  },
  boxTitleFill: {
    flexDirection: 'row',
    marginLeft: 16,
    marginEnd: 16,
    marginTop: 20,
    marginBottom: 20,
    alignItems: 'center',
  },
  boxArrow: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  boxIndicatorFill: {
    backgroundColor: '#d8d8d8',
    height: 10,
  },
  containerBasicInfo: {flexDirection: 'row', marginBottom: 20},
  boxBasicInfo: {flex: 1, marginEnd: 10},
  txtTitleBasicInfo: {color: '#757575', marginBottom: 5, fontSize: 16},
  boxInputBasicInfo: {
    width: '100%',
    height: 44,
    borderColor: '#d8d8d8',
    borderWidth: 1,
    borderRadius: 6,
  },
  boxPickerBasicInfo: {
    width: '100%',
    height: 44,
    borderColor: '#d8d8d8',
    borderWidth: 1,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 5,
    paddingEnd: 10,
  },
  txtInputBasicInfo: {
    height: 44,
    width: '100%',
    color: '#2b2b2b',
    fontSize: 16,
    paddingEnd: 5,
    paddingStart: 5,
  },
  txtPicker: {
    flex: 1,
    fontSize: 16,
  },
  btSelectGender: {
    textAlign: 'center',
    color: '#fff',
    fontSize: 18,
    paddingTop: 8,
    paddingBottom: 8,
    paddingEnd: 25,
    paddingStart: 25,
  },
});
